builds:
  - binary: gpsync
    goos:
      - linux
    goarch:
      - amd64
nfpms:
  -
    id: foo

    package_name: gpsync

    file_name_template: "{{ .ConventionalFileName }}"

    builds:
      - foo
      - bar

    vendor: ""

    homepage: https://github.com/rjsanghamitra/gpsync/

    maintainer: Sanghamitra <rjsanghamitra@gmail.com>

    description: |-
      This is a command line tool that creates a backup of Google Photos in your local system.

    license: MIT

    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Since GoReleaser v1.11.
      - archlinux  # Since GoReleaser v1.13.

    dependencies:
      - git
      - zsh

    provides:
      - bar

    recommends:
      - bzr
      - gtk

    suggests:
      - cvs
      - ksh

    conflicts:
      - svn
      - bash

    replaces:
      - fish

    bindir: /usr/bin

    epoch: 2

    prerelease: beta1

    version_metadata: git

    release: 1

    section: default

    priority: extra

    meta: true

    changelog: ./foo.yml

    contents:
      - src: path/to/foo
        dst: /usr/bin/foo

      - src: path/to/foo.conf
        dst: /etc/foo.conf
        type: config

      - src: /sbin/foo
        dst: /usr/bin/foo
        type: "symlink"

      - src: path/to/local/bar.conf
        dst: /etc/bar.conf
        type: "config|noreplace"

      - src: path/{{ .Os }}-{{ .Arch }}/bar.conf
        dst: /etc/foo/bar-{{ .ProjectName }}.conf

      - dst: /etc/casper.conf
        type: ghost
      - dst: /var/log/boo.log
        type: ghost

      - src: path/to/rpm/file.conf
        dst: /etc/file.conf
        type: "config|noreplace"
        packager: rpm
      - src: path/to/deb/file.conf
        dst: /etc/file.conf
        type: "config|noreplace"
        packager: deb
      - src: path/to/apk/file.conf
        dst: /etc/file.conf
        type: "config|noreplace"
        packager: apk

      - src: path/to/foo
        dst: /usr/local/foo
        file_info:
          mode: 0644
          mtime: 2008-01-02T15:04:05Z
          owner: notRoot
          group: notRoot

      - src: ./foo/bar/*
        dst: /usr/local/myapp/

      - dst: /some/dir
        type: dir
        file_info:
          mode: 0700

    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"

    overrides:
      deb:
        depends:
          - baz (>= 1.2.3-0)
          - some-lib-dev
      rpm:
        depends:
          - baz >= 1.2.3-0
          - some-lib-devel
      apk:

    rpm:
      scripts:
        pretrans: ./scripts/pretrans.sh
        posttrans: ./scripts/posttrans.sh

      summary: Explicit Summary for Sample Package

      group: Unspecified
      packager: GoReleaser <staff@goreleaser.com>

      compression: lzma

      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'

    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

      scripts:
        rules: foo.sh
        templates: templates

      triggers:
        interest:
          - some-trigger-name
        activate:
          - another-trigger-name

      breaks:
        - some-package

      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'

        type: origin

    apk:
      scripts:
        preupgrade: ./scripts/preupgrade.sh
        postupgrade: ./scripts/postupgrade.sh

      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'

        key_name: origin

    archlinux:
      scripts:
        preupgrade: ./scripts/preupgrade.sh
        postupgrade: ./scripts/postupgrade.sh

      pkgbase: foo

      packager: GoReleaser <staff@goreleaser.com>